// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCUfypH2AMOQJiug5zW15Qc0S47mJ-FbXw',
    appId: '1:635068110518:web:7041b190d298c30fdb3817',
    messagingSenderId: '635068110518',
    projectId: 'arifa-medikal-klinik',
    authDomain: 'arifa-medikal-klinik.firebaseapp.com',
    storageBucket: 'arifa-medikal-klinik.appspot.com',
    measurementId: 'G-1LK2RYTDC2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDGkCmmjYa6MQpnrxwrn7IshpdzOLR2UWs',
    appId: '1:603088810081:android:249b74d705f17a52f3fa20',
    messagingSenderId: '603088810081',
    projectId: 'arifa-medikal-klinik-c8675',
    storageBucket: 'arifa-medikal-klinik-c8675.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDJZ-op1LYq60X8Hc2UTsmKCq7M55CySek',
    appId: '1:635068110518:ios:07d1f1a5d80d2741db3817',
    messagingSenderId: '635068110518',
    projectId: 'arifa-medikal-klinik',
    storageBucket: 'arifa-medikal-klinik.appspot.com',
    iosClientId:
        '635068110518-unv2h39mb96ok9dusr5areoro56g0icl.apps.googleusercontent.com',
    iosBundleId: 'com.example.arifaMedikalKlink3',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDJZ-op1LYq60X8Hc2UTsmKCq7M55CySek',
    appId: '1:635068110518:ios:07d1f1a5d80d2741db3817',
    messagingSenderId: '635068110518',
    projectId: 'arifa-medikal-klinik',
    storageBucket: 'arifa-medikal-klinik.appspot.com',
    iosClientId:
        '635068110518-unv2h39mb96ok9dusr5areoro56g0icl.apps.googleusercontent.com',
    iosBundleId: 'com.example.arifaMedikalKlink3',
  );
}
